# Generated by Django 5.0.3 on 2024-03-28 22:22

import django.core.validators
import django.db.models.deletion
import members.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Name")),
                ("last_name", models.CharField(max_length=100, verbose_name="Surname")),
                (
                    "social_id",
                    models.CharField(
                        max_length=16,
                        validators=[members.models.check_italian_social_id],
                        verbose_name="Social ID",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        max_length=1,
                        verbose_name="Gender",
                    ),
                ),
                ("birth_date", models.DateField(verbose_name="Birth Date")),
                (
                    "birth_city",
                    models.CharField(
                        help_text="City/municipality or foreign country where Member is born",
                        max_length=150,
                        verbose_name="Birth City",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        help_text="Phone Number, use only digits, +, -, space and parenthesis",
                        max_length=50,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^(00|\\+)?((\\d+|\\(\\d+\\))[ \\-]?)+\\d$",
                                "Use only plus sign (at start), dashes (-), spaces and parenthesis",
                            )
                        ],
                        verbose_name="Phone Number",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="member",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Member",
                "verbose_name_plural": "Members",
            },
        ),
    ]
